### ISSUE TITLE
Failing test, possible problem with executing multiple statements

### ISSUE THREAD

**Issue by basti1302** [jtdaugherty/dbmigrations-mysql#1]
The test `applyMigrationSuccess` fails with the following error:

### Error in:   0:MySQL backend tests
ConnectionError {errFunction = "query", errNumber = 1064, errMessage = "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE valid2 (a int)' at line 1"}
Cases: 1  Tried: 1  Errors: 1  Failures: 0

At first I though that maybe the way the [applyMigration](
https://github.com/basti1302/dbmigrations-mysql/blob/master/src/Database/Schema/Migrations/Backend/MySQL.hs#L59-L69) function is implemented is not capable of executing a migration that contains multiple statements (separated by a semicolon) because the test passes if one removes the second "CREATE TABLE" statement (and the corresponding expectation from the check for installed tables) from the migration that is constructed in this test. This can't be the whole truth, though, because having multiple statements in one migration works fine when using `moo-mysql`. I did not investigate further.

Another aspect that is maybe worth noting: I suspect this test _never_ actually ran successfully, because the way BackendTest.hs is implemented _it stops on the first test failure_ without even attempting the to run the rest of the tests. `applyMigrationFailure` always failed, so most of the tests probably never ran at all. This is backed up by the fact that `revertMigrationFailure` and `revertMigrationNothing` also failed once the other test failures were removed. Those failed with 

```
### Error in:   0:MySQL backend tests
QueryError {qeMessage = "execute resulted in 1-column result", qeQuery = "SELECT 1"}
Cases: 1  Tried: 1  Errors: 1  Failures: 0
```

because apparently the `SELECT 1` or similar that were meant to act as a noop caused a problem with a result that was left unconsumed, see commit [3cdb029c5ad09517b199a2ede5a956fc76426da3](https://github.com/basti1302/dbmigrations-mysql/commit/3cdb029c5ad09517b199a2ede5a956fc76426da3#diff-bf04698ff32b12a76835d91696ad85d8L126)
 for a proper MySQL noop.

(In retrospect, it might have been a good idea to remove the known failing test case right from the start).

**Comment by basti1302** [comment]
Summoning @ocharles here: You [implemented](https://github.com/jtdaugherty/dbmigrations/pull/26) the original MySQL support for the [dbmigrations](https://github.com/jtdaugherty/dbmigrations) package, including tests. It seems that in addition to the one expected failure (which fails because MySQL does not support transactions for DDL statements) there is also one very unexpected failure.

Maybe you can figure out what's going on here?

Background story: Support for specific databases is factored out into individual wrapper packages, see here: https://github.com/jtdaugherty/dbmigrations/pull/32

This is the wrapper package for MySQL, so most of the code in this package somehow was actually written by you at some point. ;-) 

As you can see in the discussion about PR 32 of dbmigrations, Jonathan thinks about dropping support for MySQL again, so maybe this is some motivation to take a short look :)

**Comment by jtdaugherty** [comment]
I've kicked the can by just removing the second table creation from that migration. It isn't crucial to what the test is doing anyway. That, combined with the transactional DDL check in the test suite, means that the MySQL backend for dbmigrations now passes the test suite. (If there's more to this ticket, I'm interested - but I don't think it needs to hold anything up.)

**Comment by basti1302** [comment]
That's probably the best solution right now. I thought about doing that myself but didn't want to make the call.
